candlestick_patterns = {
    'CDL2CROWS': ['Two Crows', '两只乌鸦'],
    'CDL3BLACKCROWS': ['Three Black Crows', '三只乌鸦'],
    'CDL3INSIDE': ['Three Inside Up/Down', '三个内上/下'],
    'CDL3LINESTRIKE': ['Three-Line Strike', '三线罢工'],
    'CDL3OUTSIDE': ['Three Outside Up/Down', '三个外上/下'],
    'CDL3STARSINSOUTH': ['Three Stars In The South', '南方的三星'],
    'CDL3WHITESOLDIERS': ['Three Advancing White Soldiers', '三名前进的白人士兵'],
    'CDLABANDONEDBABY': ['Abandoned Baby', '弃婴'],
    'CDLADVANCEBLOCK': ['Advance Block', '前进挡'],
    'CDLBELTHOLD': ['Belt-hold', '安全带'],
    'CDLBREAKAWAY': ['Breakaway', '脱离'],
    'CDLCLOSINGMARUBOZU': ['Closing Marubozu', '关闭丸子'],
    'CDLCONCEALBABYSWALL': ['Concealing Baby Swallow', '隐藏小燕子'],
    'CDLCOUNTERATTACK': ['Counterattack', '反击'],
    'CDLDARKCLOUDCOVER': ['Dark Cloud Cover', '乌云'],
    'CDLDOJI': ['Doji', '十字线'],
    'CDLDOJISTAR': ['Doji Star', '道士之星'],
    'CDLDRAGONFLYDOJI': ['Dragonfly Doji', '蜻蜓十字星'],
    'CDLENGULFING': ['Engulfing Pattern', '吞没模式'],
    'CDLEVENINGDOJISTAR': ['Evening Doji Star', '夜道士之星'],
    'CDLEVENINGSTAR': ['Evening Star', '晚星'],
    'CDLGAPSIDESIDEWHITE': ['Up/Down-gap side-by-side white lines', '上/下间隙并排白线'],
    'CDLGRAVESTONEDOJI': ['Gravestone Doji', '墓碑十字线'],
    'CDLHAMMER': ['Hammer', '锤子'],
    'CDLHANGINGMAN': ['Hanging Man', '绞刑犯'],
    'CDLHARAMI': ['Harami Pattern', '孕线'],
    'CDLHARAMICROSS': ['Harami Cross Pattern', '十字孕线'],
    'CDLHIGHWAVE': ['High-Wave Candle', '高频蜡烛'],
    'CDLHIKKAKE': ['Hikkake Pattern', '海克图案'],
    'CDLHIKKAKEMOD': ['Modified Hikkake Pattern', '改进的海克图案'],
    'CDLHOMINGPIGEON': ['Homing Pigeon', '信鸽'],
    'CDLIDENTICAL3CROWS': ['Identical Three Crows', '一模一样的三只乌鸦'],
    'CDLINNECK': ['In-Neck Pattern', '领式'],
    'CDLINVERTEDHAMMER': ['Inverted Hammer', '倒置锤子'],
    'CDLKICKING': ['Kicking', '踢'],
    'CDLKICKINGBYLENGTH': ['Kicking - bull/bear determined by the longer marubozu',
                           '踢-公牛/熊由较长的丸子决定'],
    'CDLLADDERBOTTOM': ['Ladder Bottom', '梯底'],
    'CDLLONGLEGGEDDOJI': ['Long Legged Doji', '长腿道士'],
    'CDLLONGLINE': ['Long Line Candle', '长线蜡烛'],
    'CDLMARUBOZU': ['Marubozu', '丸子'],
    'CDLMATCHINGLOW': ['Matching Low', '匹配低'],
    'CDLMATHOLD': ['Mat Hold', '垫舱'],
    'CDLMORNINGDOJISTAR': ['Morning Doji Star', '晨间道场之星'],
    'CDLMORNINGSTAR': ['Morning Star', '晨星'],
    'CDLONNECK': ['On-Neck Pattern', '论颈部花纹'],
    'CDLPIERCING': ['Piercing Pattern', '穿孔模式'],
    'CDLRICKSHAWMAN': ['Rickshaw Man', '黄包车夫'],
    'CDLRISEFALL3METHODS': ['Rising/Falling Three Methods', '上升/下降三种方法'],
    'CDLSEPARATINGLINES': ['Separating Lines', '分隔线'],
    'CDLSHOOTINGSTAR': ['Shooting Star', '流星'],
    'CDLSHORTLINE': ['Short Line Candle', '短线蜡烛'],
    'CDLSPINNINGTOP': ['Spinning Top', '陀螺'],
    'CDLSTALLEDPATTERN': ['Stalled Pattern', '失速模式'],
    'CDLSTICKSANDWICH': ['Stick Sandwich', '棒状三明治'],
    'CDLTAKURI': ['Takuri (Dragonfly Doji with very long lower shadow)',
                  '塔库里（蜻蜓道场，阴影很长）'],
    'CDLTASUKIGAP': ['Tasuki Gap', '塔苏基峡'],
    'CDLTHRUSTING': ['Thrusting Pattern', '逆冲样式'],
    'CDLTRISTAR': ['Tristar Pattern', '三星图案'],
    'CDLUNIQUE3RIVER': ['Unique 3 River', '独特的3河'],
    'CDLUPSIDEGAP2CROWS': ['Upside Gap Two Crows', '两只乌鸦'],
    'CDLXSIDEGAP3METHODS': ['Upside/Downside Gap Three Methods', '上行/下行缺口三种方法']}
